<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->


# Lab: Regressão Logística

Referências e Materiais úteis para este Lab: *ver notas de aula de regressão logística e linear*.

<br>

---





# Caso: **Predição de Diagnósticos a partir de Dados de Imagens**


https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

Os dados acima são características computadas a partir de uma imagem digitalizada por *agulha fina* (PAAF) de uma massa mamária. Eles descrevem características dos núcleos celulares presentes na imagem e classificam os tumores como malignos ou benignos.



<img src="https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/blob/main/images/ClassificationBreastCancer.PNG?raw=true" width=1200, align="right">

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
#@markdown **Set Up Lab** (*run this before continue*)
breast = pd.read_csv('https://github.com/Rogerio-mack/Machine-Learning-I/raw/main/data/breast.csv')

from sklearn.model_selection import train_test_split

seed = 1984
X_train, X_test, y_train, y_test = train_test_split(breast.drop(columns=['diagnosis']), breast.diagnosis, test_size=0.50, stratify=breast.diagnosis, random_state=seed)

breast = pd.concat([X_train, y_train],axis=1)
new_breast = X_test

breast.to_csv('breast.csv',index=False)

new_breast['diagnosis'] = '?'
new_breast.to_csv('new_breast.csv',index=False)
y_test.to_csv('new_breast_answers.csv',index=False)

new_breast_answers = pd.read_csv('new_breast_answers.csv')


E você empregará os dados já tratados no set up acima, com os dataframes `breast` e `new_breast`. A idea aqui é empregar os dados de `breast` para estimar as classes dos novos casos desconhecidos de `new_breast`.



In [ ]:
breast.head()

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
397    89296        11.46         18.16           73.59      403.1   
146   894090        12.18         14.08           77.25      461.4   
207   897132        11.22         19.86           71.94      387.3   
446   894335        12.43         17.00           78.60      477.3   
63   9013594        13.66         15.15           88.27      580.6   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
397          0.08853           0.07694        0.033440             0.015020   
146          0.07734           0.03212        0.011230             0.005051   
207          0.10540           0.06779        0.005006             0.007583   
446          0.07557           0.03454        0.013420             0.016990   
63           0.08268           0.07548        0.042490             0.024710   

     symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
397         0.1411  ...          21.61            82.69       489.8   
146         0.1673  ...          16.47            81.60       513.1   
207         0.1940  ...          25.78            76.91       436.1   
446         0.1472  ...          20.21            81.76       515.9   
63          0.1792  ...          19.64            97.96       657.0   

     smoothness_worst  compactness_worst  concavity_worst  \
397           0.11440            0.17890          0.12260   
146           0.10010            0.05332          0.04116   
207           0.14240            0.09669          0.01335   
446           0.08409            0.04712          0.02237   
63            0.12750            0.31040          0.25690   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
397               0.05509          0.2208                  0.07638          B  
146               0.01852          0.2293                  0.06037          B  
207               0.02022          0.3292                  0.06522          B  
446               0.02832          0.1901                  0.05932          B  
63                0.10540          0.3387                  0.09638          B  

[5 rows x 32 columns]

In [ ]:
new_breast.head()

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
426  8711803       19.190         15.94          126.30     1157.0   
424   924342        9.333         21.94           59.01      264.0   
472   903011       11.270         15.50           73.38      392.0   
372   857156       13.490         22.30           86.91      561.0   
284    87880       13.810         23.75           91.56      597.8   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
426          0.08694           0.11850         0.11930              0.09667   
424          0.09240           0.05605         0.03996              0.01282   
472          0.08365           0.11140         0.10070              0.02757   
372          0.08752           0.07698         0.04751              0.03384   
284          0.13230           0.17680         0.15580              0.09176   

     symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
426         0.1741  ...          17.81           146.60      1495.0   
424         0.1692  ...          25.05            62.86       295.8   
472         0.1810  ...          18.93            79.73       450.0   
372         0.1809  ...          31.82            99.00       698.8   
284         0.2251  ...          41.85           128.50      1153.0   

     smoothness_worst  compactness_worst  concavity_worst  \
426            0.1124            0.20160          0.22640   
424            0.1103            0.08298          0.07993   
472            0.1102            0.28090          0.30210   
372            0.1162            0.17110          0.22820   
284            0.2226            0.52090          0.46460   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
426               0.17770          0.2443                  0.06251          ?  
424               0.02564          0.2435                  0.07393          ?  
472               0.08272          0.2157                  0.10430          ?  
372               0.12820          0.2871                  0.06917          ?  
284               0.20130          0.4432                  0.10860          ?  

[5 rows x 32 columns]

# Exercício

Empregue a regressão logística para determinar o diagnóstico provável dos novos casos.

## Treine o modelo

Q1. Empregue `max_iter=10000` e observe que **ao menos 1 atributo (além do atributo alvo), não pode ser empregado para entrada do treinamento**. Por que?

Q2. Qual quantos são e qual a soma dos coeficientes da regressão logística obtidos após o treinamento? (Dica: os coeficientes inclui também o coeficiente independente.)

Q3. Quantos atributos são positivamente relacionados com o aspecto benigno do tumor?

Q4. Quais os 5 atributos que mais contribuem positivamente para o aspecto maligno do tumor? (Dica: empregue `np.argsort`)

Q5. Qual a acuracidade do modelo sobre o conjunto de treinamento empregado?



In [ ]:
from sklearn.linear_model import LogisticRegression

# Entradas e Saídas
X = breast.drop(columns=['id','diagnosis'])
y = breast['diagnosis']

# Definição
clf = LogisticRegression(max_iter=10000)

# Treinamento
clf.fit(X,y)


LogisticRegression(max_iter=10000)

In [ ]:
clf.coef_ , clf.intercept_

(array([[-0.40904337, -0.26933757,  0.07466332, -0.01224195,  0.10100283,
          0.13420778,  0.29406006,  0.14500842,  0.13020851,  0.021863  ,
          0.01290616, -0.51650729,  0.13903866,  0.08315993,  0.016286  ,
         -0.04190755,  0.03639837,  0.02147106, -0.00761124, -0.01268737,
         -0.26926103,  0.39039411,  0.0831176 ,  0.0157431 ,  0.20999927,
          0.54706637,  0.94859393,  0.33300661,  0.23864061,  0.06094655]]),
 array([-18.88689361]))

In [ ]:
clf.coef_.sum() + clf.intercept_[0]

-16.387708720707053

In [ ]:
clf.coef_.shape[1] + len(clf.intercept_)

31

In [ ]:
np.sum( clf.coef_ > 0 )

22

In [ ]:
clf.classes_

array(['B', 'M'], dtype=object)

In [ ]:
list1 = X.columns[ list(np.argsort( clf.coef_ )[0][0:5]) ]
list1

Index(['texture_se', 'radius_mean', 'texture_mean', 'radius_worst',
       'compactness_se'],
      dtype='object')

In [ ]:
X.columns[ np.argmin( clf.coef_ ) ]

'texture_se'

In [ ]:
# Avaliação
y_pred = clf.predict(X)

# Acuracidade
print(sum(y_pred == y) / len(y))

# OU

# Acuracidade
print(clf.score(X,y))

# OU ainda
from sklearn.metrics import accuracy_score

print(accuracy_score(y, y_pred))

0.937037037037037
0.937037037037037
0.937037037037037


## Predição dos novos casos

Faça a predição dos novos casos.

Q6. Quantos casos benignos e quandos malignos você obteve?

In [ ]:
# Avaliação
y_pred = clf.predict(new_breast.drop(columns=['id','diagnosis']))

In [ ]:
np.unique(y_pred,return_counts=True)

(array(['B', 'M'], dtype=object), array([170, 100]))

Q7. O dataset abaixo contém as respostas dos novos casos. Compare com suas predições. Qual o percentual de acerto desse modelo sobre esse conjunto? É o mesmo sobre que o resultado anterior? O que você pode dizer sobre esse resultado?


In [ ]:
new_breast_answers.head()

diagnosis
0         M
1         B
2         B
3         B
4         M

In [ ]:
print(accuracy_score(new_breast_answers.diagnosis, y_pred))

0.9555555555555556


## Treine o modelo com os dados normalizado (`minmax`)

Na norma `minmax` cada atributo deve estar em uma escala de $[0,1]$.

Q8. Para o novo modelo, quantos atributos são positivamente relacionados com o aspecto benigno do tumor?

Q9. Para o novo modelo, quais os 5 atributos que mais contribuem positivamente para o aspecto maligno do tumor? São os mesmos da lista anteriormente obtida? (Dica: empregue `np.argsort`)

>> **A normalização, mesmo não sendo obrigatória alguns modelos permite uma melhor interpretabilidade dos resultados, por exemplo da participação de cada atributo na determinação da variável alvo.**

Q10. Para o novo modelo, qual a acuracidade do modelo sobre o conjunto de treinamento empregado?

Q11. Quantos casos B e M são obtidos com o novo modelo para o conjunto de novos casos?

Q12. Quantos casos B seriam obtidos se aumentarmos a margem segurança requerendo uma probabilidade mínima de 60% para os casos benignos (Dica: empregue `clf.predict_proba`).

In [ ]:
from sklearn.linear_model import LogisticRegression

# Entradas e Saídas
X = breast.drop(columns=['id','diagnosis'])
X = X / X.max()
y = breast['diagnosis']

# Definição
clf = LogisticRegression(max_iter=10000)

# Treinamento
clf.fit(X,y)


LogisticRegression(max_iter=10000)

In [ ]:
np.sum( clf.coef_ > 0 )

25

In [ ]:
list2 = X.columns[ list(np.argsort( clf.coef_ )[0][0:5]) ]
list2

Index(['fractal_dimension_se', 'symmetry_se', 'fractal_dimension_mean',
       'compactness_se', 'concavity_se'],
      dtype='object')

In [ ]:
list1 == list2

array([False, False, False, False, False])

In [ ]:
# Avaliação
y_pred = clf.predict(X)

# Acuracidade
print(sum(y_pred == y) / len(y))

# OU

# Acuracidade
print(clf.score(X,y))

# OU ainda
from sklearn.metrics import accuracy_score

print(accuracy_score(y, y_pred))

0.9555555555555556
0.9555555555555556
0.9555555555555556


In [ ]:
# Avaliação

X_new = new_breast.drop(columns=['id','diagnosis'])
X_new = X_new / breast.drop(columns=['id','diagnosis']).max()
y_pred = clf.predict(X_new)

In [ ]:
np.unique(y_pred,return_counts=True)

(array(['B', 'M'], dtype=object), array([179,  91]))

In [ ]:
print(accuracy_score(new_breast_answers.diagnosis, y_pred))

0.9592592592592593


In [ ]:
# Avaliação

X_new = new_breast.drop(columns=['id','diagnosis'])
X_new = X_new / breast.drop(columns=['id','diagnosis']).max()
y_predproba = clf.predict_proba(X_new)
y_predproba[0:10]

array([[0.16409565, 0.83590435],
       [0.98185767, 0.01814233],
       [0.94620369, 0.05379631],
       [0.72763062, 0.27236938],
       [0.04784234, 0.95215766],
       [0.08415371, 0.91584629],
       [0.50000355, 0.49999645],
       [0.00720785, 0.99279215],
       [0.95878736, 0.04121264],
       [0.29283434, 0.70716566]])

In [ ]:
y_predproba[0:5]

array([[0.16409565, 0.83590435],
       [0.98185767, 0.01814233],
       [0.94620369, 0.05379631],
       [0.72763062, 0.27236938],
       [0.04784234, 0.95215766]])

In [ ]:
np.sum( y_predproba[:,0] > 0.6 )

172

## Regressão Logística $\times$ Regressão Linear (RESOLVIDO)

Substitua os valores de `diagnosis` por `'B':1,'M':0` e converta para um tipo numérico (`float`, por exemplo). Os valores agora são numéricos e você pode, então, aplicar uma regressão linear para estimar uma função linear $f(X)$, com  $y=0$, se $f(X) > 0.5$ e $y=1$, se $f(X) \le 0.5$.

>> **Embora neste caso os resultados sejam os mesmos, a regressão linear apresenta em geral um desempenho bastante pior quando aplicada em problemas de classificação, em especial para as classes de valores próximos.**

In [ ]:
breast['diagnosis'] = breast['diagnosis'].replace({'B':1,'M':0})
breast['diagnosis'] = breast['diagnosis'].astype('float')

breast['diagnosis']

397    1.0
146    1.0
207    1.0
446    1.0
63     1.0
      ... 
201    1.0
487    0.0
318    0.0
301    0.0
89     0.0
Name: diagnosis, Length: 270, dtype: float64

In [ ]:
from sklearn.linear_model import LogisticRegression

# Entradas e Saídas
X = breast.drop(columns=['id','diagnosis'])
X = X / X.max()
y = breast['diagnosis']

# Definição
clf = LogisticRegression(max_iter=10000)

# Treinamento
clf.fit(X,y)

print(clf.score(X,y))

0.9555555555555556


In [ ]:
from sklearn.linear_model import LinearRegression

# Entradas e Saídas
X = breast.drop(columns=['id','diagnosis'])
X = X / X.max()
y = breast['diagnosis']

# Definição
clf = LinearRegression()

# Treinamento
clf.fit(X,y)

print(clf.score(X,y))

# Avaliação
y_pred = clf.predict(X) > 0.5

# Acuracidade
print(sum(y_pred == y) / len(y))

0.7857959564255844
0.9555555555555556
